# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Validate
    jobs:
    - job: Validate
      steps:
      - publish: 1-terraform
        artifact: terraform_out
    
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.11.11'

      - task: TerraformCLI@0
        inputs:
            command: 'init'
            backendType: 'azurerm'
            backendServiceArm: 'Visual Studio Enterprise'
            ensureBackend: true
            backendAzureRmResourceGroupName: 'AKSTerraform-RG'
            backendAzureRmResourceGroupLocation: 'EastUS2'
            backendAzureRmStorageAccountName: 'stgaksterraformdemo'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'demo.terraform.tfstte'

      - task: TerraformCLI@0
        inputs:
          command: 'validate'